import Head from "next/head";
import React from "react";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { createPopper } from "@popperjs/core";

export default function Home() {
  const [dropdownPopoverShow, setDropdownPopoverShow] = React.useState(false);
  const btnDropdownRef = React.createRef();
  const popoverDropdownRef = React.createRef();
  const openDropdownPopover = () => {
    createPopper(btnDropdownRef.current, popoverDropdownRef.current, {
      placement: "bottom-start",
    });
    setDropdownPopoverShow(true);
  };
  const closeDropdownPopover = () => {
    setDropdownPopoverShow(false);
  };
  return (
    <>
      <Head>
        <title>LibraryApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-gray-800 bg-white relative overflow-hidden h-screen">
        <header className="h-24 sm:h-32 flex items-center z-30 w-full">
          <div className="container mx-auto px-6 flex items-center justify-between">
            <div className="uppercase text-gray-800 dark:text-white font-black text-3xl">
              <h1>Library App</h1>
            </div>
            <div className="flex items-center">
              <nav className="font-sen text-gray-800 dark:text-white uppercase text-lg lg:flex items-center hidden">
                <a href="/" className="py-2 px-6 flex text-indigo-500 border-b-2 border-indigo-500">
                  Home
                </a>
                <a href="/books" className="py-2 px-6 flex hover:text-indigo-500">
                  Books
                </a>
                <a href="/login" className="py-2 px-6 flex hover:text-indigo-500">
                  Sign in
                </a>
                <a href="/register" className="py-2 px-6 flex hover:text-indigo-500">
                  Sign Up
                </a>
              </nav>
              <a
                className="md:text-white md:hover:text-blueGray-200 text-white px-3 py-4 md:py-2 flex items-center text-xs uppercase font-bold cursor-pointer lg:hidden"
                ref={btnDropdownRef}
                onClick={(e) => {
                  e.preventDefault();
                  dropdownPopoverShow ? closeDropdownPopover() : openDropdownPopover();
                }}
              >
                Menu
              </a>
              <div ref={popoverDropdownRef} className={(dropdownPopoverShow ? "block " : "hidden ") + "bg-white text-base z-50 float-left py-2 list-none text-left rounded shadow-lg min-w-48"}>
                <a href="/" className="py-2 px-6 flex text-indigo-500 border-b-2 border-indigo-500">
                  Home
                </a>
                <a href="/books" className="py-2 px-6 flex hover:text-indigo-500">
                  Books
                </a>
                <a href="/login" className="py-2 px-6 flex hover:text-indigo-500">
                  Sign in
                </a>
                <a href="/register" className="py-2 px-6 flex hover:text-indigo-500">
                  Sign Up
                </a>
              </div>
            </div>
          </div>
        </header>
        <div className="bg-white dark:bg-gray-800 flex relative z-20 items-center">
          <div className="container mx-auto px-6 flex flex-col justify-between items-center relative py-8">
            <div className="flex flex-col">
              <h1 className="font-light w-full uppercase text-center text-4xl sm:text-5xl dark:text-white text-gray-800">See What Books That Availible on The Library</h1>
              <h2 className="font-light max-w-2xl mx-auto w-full text-xl dark:text-white text-gray-500 text-center py-8">This Library app gives you the simplest way to see what books that Availible on the library</h2>
              <div className="flex items-center justify-center mt-4">
                <a href="/books" className="uppercase py-2 my-8 px-4 bg-gray-600 border-2 border-transparent text-white text-md mr-4 hover:bg-gray-900">
                  Get started
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className="w-full mx-auto mt-6 md:mt-0 relative">
          <img src="https://images.unsplash.com/photo-1516888693095-f0e05366ddc6?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=880&q=80" class="max-w-xs md:max-w-2xl m-auto" />
        </div>
      </main>
    </>
  );
}
